version: '3.8'

services:
  web:
    build: .
    command: gunicorn hr_system.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DEBUG=False
      - POSTGRES_DB=hr_db
      - POSTGRES_USER=hr_user
      - POSTGRES_PASSWORD=hr_password
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=hr_db
      - POSTGRES_USER=hr_user
      - POSTGRES_PASSWORD=hr_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d hr_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
